name: Build App
on:
  release:
    types: [published]
  workflow_dispatch:
jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest
    steps:
    - name: Clone repository
      uses: actions/checkout@v4
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
          channel: stable
    - name: Start building
      run: flutter build windows
    - name: Generate inno setup script
      run: dart windows/installer/generate_inno.dart
    - name: Compile .ISS to .EXE Installer
      uses: Minionguyjpro/Inno-Setup-Action@v1.2.4
      with:
        path: build/innosetup.iss
        options: /O+
    - name: Upload release asset
      run: ls build/windows
