name: Upload assets and sync to gitee

on:
  release:
    types: [published]

jobs:
  build:
    name: Build app and upload artifacts
    uses: joodo/bunga_player/.github/workflows/build.yml@main

  upload-release-assets:
    name: Upload release assets
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        run_id: ${{ needs.build.outputs.workflow_id }}
        path: release-assets
        merge-multiple: true

    - name: Upload release binaries
      env:
          GH_TOKEN: ${{ github.token }}
      run: |
          gh release upload ${{ github.event.release.tag_name }} release-assets/*

  sync-gitee:
    name: Sync Gitee
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        run_id: ${{ needs.build.outputs.workflow_id }}
        path: release-assets
        merge-multiple: true

    - name: Sync code to Gitee
      uses: abersheeran/sync-gitee-mirror@v1-beta
      with:
        repository: joodo2/bunga_player
        username: ${{ secrets.GITEE_USERNAME }}
        password: ${{ secrets.GITEE_PASSWORD }}

    - name: Remove Gitee latest release
      run: >
        shopt -s lastpipe

        curl -X GET 
        -header 'Content-Type: application/json;charset=UTF-8'
        'https://gitee.com/api/v5/repos/joodo2/bunga_player/releases/latest?access_token=${{ secrets.GITEE_TOKEN }}' 
        | jq -r '.id'
        | read latest_id
        
        if [[ -n "$latest_id" ]]; then

        curl -X DELETE
        --header 'Content-Type: application/json;charset=UTF-8'
        'https://gitee.com/api/v5/repos/joodo2/bunga_player/releases/$latest_id?access_token=${{ secrets.GITEE_TOKEN }}' 

        fi
    - name: Create Gitee release
      run: >
        shopt -s lastpipe

        curl -X POST --header 'Content-Type: application/json;charset=UTF-8'
        'https://gitee.com/api/v5/repos/joodo2/bunga_player/releases'
        -d '{"access_token":"${{ secrets.GITEE_TOKEN }}",
        "tag_name":"${{ github.event.release.tag_name }}",
        "name":"${{ github.event.release.name }}",
        "body":"${{ github.event.release.body }}",
        "target_commitish":"main"}'
        | jq -r '.id'
        | read release_id

        echo "release_id=$release_id" >> $GITHUB_ENV
    - name: Upload assets to Gitee release
      run: >
        for i in release-assets/*; do

        curl -X POST
        "https://gitee.com/api/v5/repos/joodo2/bunga_player/releases/$release_id/attach_files"
        -F "access_token=${{ secrets.GITEE_TOKEN }}"
        -F "file=@$i"

        done
