name: Upload assets and sync to gitee

on:
  release:
    types: [published]

jobs:
  build:
    name: Build app and upload to artifacts
    uses: joodo/bunga_player/.github/workflows/build.yml@main

  upload-assets:
    name: Upload assets to release
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Make dir for assets
      run: mkdir assets
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        run_id: ${{ needs.build.outputs.workflow_id }}
        path: "$GITHUB_WORKSPACE/assets/"
        merge-multiple: true
    - run: ls "$GITHUB_WORKSPACE/assets/"
    
    - name: Upload release binaries
      env:
          GH_TOKEN: ${{ github.token }}
      run: |
          gh release upload ${{ github.event.release.tag_name }} assets/*
    